# Proxy Info
server:
  port: 8765

# Routes
zuul:
  routes:
    rest-sample: /rest/**

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://localhost:8761}/eureka/