server:
	port: 8762
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0