server:
  port: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    renewalPercentThreshold: 0.49