server:
  port: 8762

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0