server:
  port: 8762

eureka:
  instance:
    hostname: 127.0.0.1
    leaseRenewalIntervalInSeconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0